package com.surabhimarathe.interfaceautomation.artifact;

public enum ValidationCode {
    UNSUPPORTED_SCHEMA_VERSION, INVALID_ARTIFACT_VERSION, REQUIRED_FIELD, INVALID_IDENTIFIER,
    INVALID_TARGET, DUPLICATE_STEP_ID, MISSING_INPUT_REFERENCE, MISSING_OUTPUT_REFERENCE,
    INVALID_EXPRESSION, INVALID_CONSTRAINTS, UNSAFE_ACTION, MISSING_CHECKPOINT,
    MISSING_OUTPUT_EXTRACTOR, DUPLICATE_OUTPUT_EXTRACTOR, UNBOUNDED_LOCATOR_TEXT,
    INVALID_LOCATOR, INVALID_POSTCONDITION, INVALID_EXTRACTOR, INVALID_PROVENANCE,
    MALFORMED_ARTIFACT, INVALID_TRACE, UNBOUND_FILL_VALUE, AMBIGUOUS_INPUT_BINDING,
    DISCOVERY_VALUE_LEAK, INVALID_PARAMETER, INVALID_METADATA, INVALID_EXECUTION_BOUNDARY,
    DUPLICATE_OUTCOME_CODE
}
