package com.surabhimarathe.interfaceautomation.discovery;

public record ActionResult(Status status, Code code, Observation observation) {
    public enum Status { SUCCEEDED, BLOCKED, FAILED }
    public enum Code { VALUE_VERIFIED, CLICK_COMPLETED, POLICY_DENIED, STALE_OBSERVATION,
        TARGET_CHANGED, BROWSER_FAILURE, CHECKPOINT_VERIFIED, CHECKPOINT_MISMATCH,
        MEMBER_NOT_FOUND, VALIDATION_REJECTED, MAX_STEPS, DEADLINE_EXCEEDED,
        INVALID_MODEL_ACTION, MODEL_FAILURE, MODEL_HTTP_400, MODEL_HTTP_401, MODEL_HTTP_402,
        MODEL_HTTP_403, MODEL_HTTP_404, MODEL_HTTP_429, MODEL_HTTP_500, MODEL_HTTP_502,
        MODEL_HTTP_503, MODEL_HTTP_504, MODEL_INVALID_TOOL, MODEL_INVALID_ARGUMENTS,
        MODEL_UNKNOWN_TARGET, MODEL_REQUEST_FAILED, MODEL_RESPONSE_TOO_LARGE,
        MODEL_INTERRUPTED, HUMAN_REQUESTED, WAIT_COMPLETED, NO_PROGRESS, HUMAN_RESUMED,
        HANDOFF_TIMEOUT, HANDOFF_LIMIT }
}
