package com.surabhimarathe.interfaceautomation.discovery;

public enum RunState { CREATED, OBSERVING, DECIDING, ACTING, WAITING, VERIFYING,
    SUCCEEDED, BUSINESS_OUTCOME, HUMAN_REQUIRED, LIMIT_REACHED, TIMED_OUT, BLOCKED, FAILED, CLOSED }
